array = [["r2_d2",
    "aden_skirata",
    "lesser_stormtrooper",
    "ysanne_isard",
    "victorie_talik",
    "eleventh_brother",
    "darth_vader",
    "chewbacca",
    "sergeant_kreel",
    "pt_1178",
    "unknown_valtorax_character",
    "third_brother",
    "second_sister",
    "fixer",
    "thirteenth_brother",
    "dexter_jettster",
    "cyan",
    "grand_admiral_piett",
    "unknown_stemmedaxis06_character",
    "fifth_brother",
    "maze",
    "rav_bralor",
    "epsilon",
    "zeb",
    "agent66",
    "wedge_antilles",
    "cipher9",
    "thrawn",
    "corran_horn",
    "agent_kallus",
    "sixth_sister",
    "chopper",
    "han_solo",
    "ackbar",
    "grand_inquisitor",
    "rex",
    "boba_fett",
    "sabe_nabierre",
    "luke_skywalker",
    "c3po",
    "airen_cracken",
    "strzalk",
    "ninth_sister",
    "ig_88b",
    "garrick_versio",
    "axis",
    "gideon",
    "fenn_shysa",
    "boss",
    "sabine_wren",
    "mara_jade",
    "alpha_17",
    "omega",
    "kal_skirata",
    "gallius_rex",
    "twelfth_brother",
    "eli_vanto",
    "saw_garrera",
    "wolffe",
    "lando_calrissian",
    "evaarla_mereel",
    "kyle_katarn",
    "carnor_jax",
    "mission_vao",
    "x2",
    "seventh_sister",
    "jan_ors",
    "scorch",
    "lumiya",
    "rahm_kota",
    "pellaeon",
    "leia_organa","ghos_gin","janitor",
    "satele",
    "mothma",
    "bo_katan",
    "bossk",
    "snake_zapal",
    "armstrong",
    "death_troopers",
    "nom_carver",
    "samuel_rodrigues"],
         [76, 60, 7, 14, 64,
    50, 82, 68, 64, 46,
    48, 34, 33, 48, 8,
    60, 40, 48, 78, 41,
    38, 45, 60, 48, 42,
    61, 46, 69, 54, 48,
    38, 66, 72, 66, 60,
    64, 63, 52, 80, 55,
    44, 48, 40, 44, 36,
    76, 44, 34, 48, 51,
    53, 39, 40, 26, 37,
    48, 42, 48, 39, 74,
    66, 61, 48, 42, 40,
    41, 42, 48, 8, 50,
    50, 72, 60, 11, 75,
    60, 28, 59, 30, 62, 
    48, 45, 46]]
output = ""
for i,value in enumerate(array[0]):
    output+= str(value)+"*"+ str(array[1][i])+"+"
output += "money"
print("UPDATE users set tempProfit=totalstockvalue;\nUPDATE users set totalstockvalue="+output+";\nUPDATE users set tempProfit=totalstockvalue-tempProfit;\nUPDATE users set profit=profit+tempProfit;")