array = [["r2_d2",
    "aden_skirata",
    "lesser_stormtrooper",
    "ysanne_isard",
    "victorie_talik",
    "eleventh_brother",
    "darth_vader",
    "chewbacca",
    "sergeant_kreel",
    "pt_1178",
    "unknown_valtorax_character",
    "third_brother",
    "second_sister",
    "fixer",
    "thirteenth_brother",
    "dexter_jettster",
    "cyan",
    "grand_admiral_piett",
    "unknown_stemmedaxis06_character",
    "fifth_brother",
    "maze",
    "rav_bralor",
    "epsilon",
    "zeb",
    "agent66",
    "wedge_antilles",
    "cipher9",
    "thrawn",
    "corran_horn",
    "agent_kallus",
    "sixth_sister",
    "chopper",
    "han_solo",
    "ackbar",
    "grand_inquisitor",
    "rex",
    "boba_fett",
    "sabe_nabierre",
    "luke_skywalker",
    "c3po",
    "airen_cracken",
    "strzalk",
    "ninth_sister",
    "ig_88b",
    "garrick_versio",
    "axis",
    "gideon",
    "fenn_shysa",
    "boss",
    "sabine_wren",
    "mara_jade",
    "alpha_17",
    "omega",
    "kal_skirata",
    "gallius_rex",
    "twelfth_brother",
    "eli_vanto",
    "saw_garrera",
    "wolffe",
    "lando_calrissian",
    "evaarla_mereel",
    "kyle_katarn",
    "carnor_jax",
    "mission_vao",
    "x2",
    "seventh_sister",
    "jan_ors",
    "scorch",
    "lumiya",
    "rahm_kota",
    "pellaeon",
    "leia_organa","ghos_gin","janitor",
    "satele",
    "mothma",
    "bo_katan",
    "bossk",
    "snake_zapal",
    "armstrong",
    "death_troopers",
    "nom_carver",
    "samuel_rodrigues","mandalor_the_unwoke",
      "fox","x_wing",
      "tie_fighter",],
         [76, 61.2, 7.4, 14, 64,
    50, 82, 70.72, 70.2, 46,
    48, 34, 33, 53.41, 8,
    60, 41, 50, 78, 41,
    39, 44, 60, 48, 44.1,
    59.17, 46, 69, 54, 48,
    38, 66, 72, 69.8, 60,
    64, 63, 52, 80, 55,
    43, 48, 40, 45.32, 39,
    77.9, 45, 33.7, 48, 51,
    55.12, 39, 40, 26.6, 38,
    48, 43, 51, 41, 74,
    70.01, 61, 48, 42, 42.5,
    41, 44.1, 49.98, 8, 51,
    50, 74.45, 60, 7.4, 75,
    60, 25.5, 59, 30, 62, 
    49.92, 46.4, 46, 58.24,
    19, 25, 15]]
output = ""
for i,value in enumerate(array[0]):
    output+= str(value)+"*"+ str(array[1][i])+"+"
output += "money"
print("UPDATE users set tempProfit=totalstockvalue;\nUPDATE users set totalstockvalue="+output+";\nUPDATE users set tempProfit=totalstockvalue-tempProfit;\nUPDATE users set profit=profit+tempProfit;")