array = [["r2_d2",
    "aden_skirata",
    "lesser_stormtrooper",
    "ysanne_isard",
    "victorie_talik",
    "eleventh_brother",
    "darth_vader",
    "chewbacca",
    "sergeant_kreel",
    "pt_1178",
    "unknown_valtorax_character",
    "third_brother",
    "second_sister",
    "fixer",
    "thirteenth_brother",
    "dexter_jettster",
    "cyan",
    "grand_admiral_piett",
    "unknown_stemmedaxis06_character",
    "fifth_brother",
    "maze",
    "rav_bralor",
    "epsilon",
    "zeb",
    "agent66",
    "wedge_antilles",
    "cipher9",
    "thrawn",
    "corran_horn",
    "agent_kallus",
    "sixth_sister",
    "chopper",
    "han_solo",
    "ackbar",
    "grand_inquisitor",
    "rex",
    "boba_fett",
    "sabe_nabierre",
    "luke_skywalker",
    "c3po",
    "airen_cracken",
    "strzalk",
    "ninth_sister",
    "ig_88b",
    "garrick_versio",
    "axis",
    "gideon",
    "fenn_shysa",
    "boss",
    "sabine_wren",
    "mara_jade",
    "alpha_17",
    "omega",
    "kal_skirata",
    "gallius_rex",
    "twelfth_brother",
    "eli_vanto",
    "saw_garrera",
    "wolffe",
    "lando_calrissian",
    "evaarla_mereel",
    "kyle_katarn",
    "carnor_jax",
    "mission_vao",
    "x2",
    "seventh_sister",
    "jan_ors",
    "scorch",
    "lumiya",
    "rahm_kota",
    "pellaeon",
    "leia_organa","ghos_gin","janitor",
    "satele",
    "mothma",
    "bo_katan"],
         [76, 59, 6, 14, 60,
    50, 80, 68, 64, 46,
    48, 32, 32, 48, 8,
    60, 40, 48, 78, 41,
    37, 44, 60, 48, 42,
    60, 46, 68, 51, 48,
    38, 66, 72, 68, 60,
    64, 61, 52, 79, 55,
    44, 48, 40, 44, 38,
    74, 46, 34, 48, 50,
    52, 34, 40, 26, 40,
    48, 41, 46, 32, 74,
    66, 61, 50, 42, 40,
    40, 42, 48, 8, 51,
    48, 72, 60, 23.1, 75,
    65, 28]]
output = ""
for i,value in enumerate(array[0]):
    output+= str(value)+"*"+ str(array[1][i])+"+"
output += "money"
print("UPDATE users set tempProfit=totalstockvalue;\nUPDATE users set totalstockvalue="+output+";\nUPDATE users set tempProfit=totalstockvalue-tempProfit;\nUPDATE users set profit=profit+tempProfit;")